server:
  port: 8092
spring:
  application:
    name: application-stock
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      master:
        url: jdbc:mysql://192.168.1.50:3306/stock-master?characterEncoding=UTF-8&serverTimezone=GMT&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        max-active: 10
        min-idle: 5
        max-wait: 60000
        time-between-eviction-runs-millis: 3000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        filters: stat,wall,log4j2
        pool-prepared-statements: false
      slave:
        url: jdbc:mysql://192.168.1.50:3306/stock-slave?characterEncoding=UTF-8&serverTimezone=GMT&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        max-active: 10
        min-idle: 5
        max-wait: 60000
        time-between-eviction-runs-millis: 3000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        filters: stat,wall,log4j2
        pool-prepared-statements: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
#    host: 127.0.0.1
#    port: 6379
    database: 0
    timeout: 1000
    cluster:
      nodes:
       - 192.168.1.51:7001
       - 192.168.1.51:7002
       - 192.168.1.52:7003
       - 192.168.1.52:7004
       - 192.168.1.53:7005
       - 192.168.1.53:7006
      max-redirects: 10 #获取失败最大重定向次数
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数
        max-wait: 3s    #连接池最大阻塞等待时间
        min-idle: 0     #连接池的最小空闲连接
        max-idle: 10    #连接池的最大空闲连接
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.51:9092,192.168.1.52:9092,192.168.1.53:9092   #Kafka的消息中间件服务器
          auto-create-topics: true                     #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        notify-stock-delivery-input:
          destination: notify-stock-delivery
          group: stream-order-stock-group
          consumer:
            # 最多尝试处理几次，默认3
            maxAttempts: 2
            # 重试时初始避退间隔，单位毫秒，默认1000
            backOffInitialInterval: 1000
            # 重试时最大避退间隔，单位毫秒，默认10000
            backOffMaxInterval: 10000
            # 避退乘数，默认2.0
            backOffMultiplier: 2.0

mybatis:
  type-aliases-package: com.jinchi.stock.domain.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
pagehelper:
  helper-dialect: mysql

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8769/eureka/
  instance:
    prefer-ip-address: true



