server:
  port: 8094
spring:
  application:
    name: spring-OAuth2
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/spring_oauth2?characterEncoding=UTF-8&serverTimezone=GMT&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        auto-commit: true
        idle-timeout: 10000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        maximum-pool-size: 50
        connection-test-query: select 1
mybatis:
    type-aliases-package: com.jinchi.spring.oauth2.entity
    mapperLocations: classpath*:mapper/*.xml
pagehelper:
    helper-dialect: mysql