spring:
  application:
    name: eureka
server:
  port: 8769

eureka:
  server:
    enable-self-preservation: false           #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 10000      #清理间隔（单位毫秒，默认是60*1000）5秒将客户端剔除的服务在服务注册列表中剔除
    use-read-only-response-cache: false       #eureka是CAP理论种基于AP策略，为了保证强一致性关闭此切换CP默认不关闭 false关闭
  client:
    register-with-eureka: false               #false：不作为一个客户端注册到注册中心
    fetch-registry: false                     #true：可以启动，但报异常：Cannot execute request on any known server
    instance-info-replication-interval-seconds: 10
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@7
logging:
  path: logs/register
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS